### ISSUE TITLE
Valor atual de uma conta bancária

### ISSUE THREAD

**Issue by rodrigosbarretos** [organizze/api-doc#11]
Existe alguma forma de ver o valor atual (Saldo) de uma conta bancária?

**Comment by brunomafioletti** [comment]
E ai @rodrigosbarretos, então nosso README está um pouco desatualizado, mas você consegue fazer um `GET` para `/rest/v2/balances` para buscar o saldo do mês atual.

O resultado esperado é esse:
```
{
  "earnings":0,
  "expenses":0,
  "predictedEarnings":0,
  "predictedExpenses":0,
  "filteredByAccount":false,
  "previousBalance":0,
  "balance":0,
  "predictedBalance":0
}
```

Você ainda pode passar os parâmetros `start_date`, `end_date` e `account_id` para filtrar por períodos e contas que desejar.

Ex: `/rest/v2/balances?start_date=2017-08-01&end_date=2017-08-31` para buscar o saldo de Agosto.

**Comment by rodrigosbarretos** [comment]
Ah, sim. Perfeito!
Obrigado @brunomafioletti ! Deu certinho aqui!

**Comment by brunomafioletti** [comment]
Legal @rodrigosbarretos, vou fechar a issue. Qualquer dúvida é só perguntar.
