### ISSUE TITLE
Request com Axios 

### ISSUE THREAD

**Issue by lincolnlemos** [organizze/api-doc#13]
Boa tarde pessoal,

Estou tentando fazer uma requisição com o axios em um aplicação React mas estou recebendo vários erros. Faço a requisição assim:

```
const requestSl =  axios.get(
	'https://api.organizze.com.br/rest/v2/balances',
	{	
		auth: { username: ORG_SL_EMAIL, password: ORG_SL_API_KEY },
		headers: { 
			'User-Agent': 'MyPanel (lemoslincoln@gmail.com)' 
		},
	}
);
```

Estou recebendo os erros:
_Refused to set unsafe header "User-Agent"
Failed to load https://api.organizze.com.br/rest/v2/balances: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404._

As URL's e credenciais estão certinhas.. Tanto pelo navegador quanto pelo Postman ele funciona.

**Comment by esdras** [comment]
Oi Lincoln, obrigado por usar o Organizze e por reportar este problema.

Como você está fazendo essa request à partir de um browser o header 'User-Agent' não pode ser alterado. Chrome e Safari particularmente não permitem por questões de segurança. Não é um problema com a API do Organizze nem com o axios.

Eu, particularmente, recomendaria fazer as requisições pra API do Organizze no server para não expor suas credenciais.

Veja: 
https://github.com/axios/axios/issues/1231
https://stackoverflow.com/questions/27834946/set-user-agent-for-http-request-in-chrome-extension

Estou à disposição caso tenha alguma dúvida.

**Comment by lincolnlemos** [comment]
Obrigado Esdras! Deu certo aqui :)
