### ISSUE TITLE
2 api-keys por conta 

### ISSUE THREAD

**Issue by lincolnlemos** [organizze/api-doc#15]
Pessoal,

Tenho duas contas no mesmo email (exemplo: CONTA_01 e CONTA_02 )
Estou tentando acessar o endpoint /balances

Toda vez que eu crio uma api-key em uma das contas, a outra conta para de funcionar. A api-key da conta que para de funcionar começa retornar um json que não representa nenhuma das contas.

Exemplo do json:
`{
    "previous_balance": 0,
    "previous_predicted_balance": -9343,
    "balance": 0,
    "predicted_balance": -9343,
    "outcomes": 0,
    "predicted_outcomes": 0,
    "incomes": 0,
    "predicted_incomes": 0,
    "expenses": 0,
    "predicted_expenses": 0,
    "earnings": 0,
    "predicted_earnings": 0,
    "initial_amounts": 0,
    "predicted_initial_amounts": 0,
    "result": 0,
    "predicted_result": 0,
    "balances": [...]
}`

**Comment by esdras** [comment]
Oi

Estou fechando esta issue, se o problema ainda não foi resolvido, por favor, abra uma nova issue detalhando qual cliente HTTP estás usando pra acessar a API e qual a URL em questão.

Se for o browser, pode ser que há um conflito de sessão, tente algo como Postman ou Insomnia.

Desculpe a demora, esta issue acabou ficando pra trás 😞

**Comment by lincolnlemos** [comment]
@esdras 
Nesse caso eu estava usando o Postman.
Acabei descontinuando a ideia pela falta de feedback.

Vou retomar os testes e te aviso em breve.
