### ISSUE TITLE
HTTP Basic: Access denied.

### ISSUE THREAD

**Issue by tihhgoncalves** [organizze/api-doc#16]
Olá pessoal.

Criei uma conta de teste. Nela, eu tô tentando listar os usuários da conta (só pra teste).
Meu link que tenta fazer isso é esse:
https://www.taticadesucesso.com.br/api/erp.php

Observa que o link está HTTPS, mas ele dá um erro, como se q requisição fosse HTTP.

Como proceder?

**Comment by esdras** [comment]
Oi @tihhgoncalves, só confirma pra mim se a conta que você está querendo acessar pertence ao Organizze ou ao Controlle, por gentileza? 

Se for uma conta no Controlle, tente acessar usando a URL https://api.controlle.com/

A documentação da API do Controlle está aqui: https://github.com/controlle/api-doc

Caso o produto seja o Organizze, por favor me informe que a gente vai investigar melhor o seu caso.

Muito obrigado por reportar.

Estou à disposição.

**Comment by tihhgoncalves** [comment]
Certo. Vou abrir lá no outro repositório o chamado. ;)
