### ISSUE TITLE
Goals endpoint

### ISSUE THREAD

**Issue by ernanielyjr** [organizze/api-doc#18]
Alguma previsão de lançamento para o endpoint que lista as metas?

**Comment by alexwbuschle** [comment]
@ernanielyjr acabou de ir pro ar esse endpoint.

Da um confere aqui `https://github.com/organizze/api-doc#listar-metas`

Abraços.

**Comment by ernanielyjr** [comment]
Show de bola pessoal. Muito obrigado!
