### ISSUE TITLE
Como identificar tipo de uma transaçao?

### ISSUE THREAD

**Issue by thales91** [organizze/api-doc#2]
Como identificar se uma transaçao é receita ou despesa na api de voces?

**Comment by solanoluz** [comment]
o amount vem negativo nas despesas.

**Comment by thales91** [comment]
e para criar uma transação como receita

**Comment by thales91** [comment]
mesmo passando valor positivo no amount ele cria como despesa quando tento criar uma receita

**Comment by solanoluz** [comment]
outcome => activity_type: 0
income => activity_type: 1

**Comment by thales91** [comment]
assim deveria criar uma receita? {"description":"Venda do Produto X","date":"2016-10-11","amount_cents":2000,"notes":"Pagamento via boleto","activity_type":1}

**Comment by esdras** [comment]
Oi @thales91 , você tem razão, é um bug, estou enviando uma correção e já te aviso.

**Comment by thales91** [comment]
muito obrigado

**Comment by esdras** [comment]
@thales91 Corrigido! basta enviar o amount_cents negativo ou positivo para criar/atualizar uma despesa/receita, esqueça o `activity_type`, é um campo interno nosso e a gente não expõe na API.

**Para criar uma despesa:**
`
POST https://api.organizze.com.br/rest/v2/transactions
{
	"amount_cents": -100,
	"description": "foo"
}`

**Para criar uma receita:**
`
POST https://api.organizze.com.br/rest/v2/transactions
{
	"amount_cents": 100,
	"description": "bar"
}`

**Comment by thales91** [comment]
ok obrigado

**Comment by thales91** [comment]
mais uma duvida é possível fazer algum tipo de filtro que não o de data e pelo id

**Comment by esdras** [comment]
Oi @thales91, ainda não é possível, podes enviar exemplos de filtros que você precisa? De preferência abrir uma nova issue.

[]s
