### ISSUE TITLE
Endpoint detalhe da fatura

### ISSUE THREAD

**Issue by marcelobelli** [organizze/api-doc#20]
Quando acesso o detalhe de uma fatura que tem transação está estourando erro 500. Acessando um mês sem lançamento responde normalmente.

URL Ex: https://api.organizze.com.br/rest/v2/credit_cards/123456/invoices/219

**Comment by alexwbuschle** [comment]
Opa @marcelobelli

Envia um email para `contato@organizze.com.br` com o `credit_card_id` e invoice que deu o problema, por favor.

Fico no aguardo :)

**Comment by marcelobelli** [comment]
Beleza, vou mandar 👍

**Comment by alexwbuschle** [comment]
E ae @marcelobelli . Subimos agora a pouco um fix para esse endpoint ;)

**Comment by marcelobelli** [comment]
Works like a charm!

Valeu!
