### ISSUE TITLE
Paginação por período não funciona

### ISSUE THREAD

**Issue by lfwroseiro** [organizze/api-doc#24]
No endpoint `\transactions`, a paginação por período retorna movimentações relativas ao mês dos parâmetros `start_date` e `end_date`, e não especificamente aos dias. 

Por exemplo, ao colocar o `end_date` como `2019-06-10`, movimentações com data posteriores ao dia 10, relativas ao mês de junho, são retornadas. O mesmo acontece para o parâmetro `start_date`.

Além disso, existe alguma forma de receber apenas as movimentações que não são de cartões de crédito? Se não, como posso definir um offset para acessar todas as movimentações do período?

Obs.: Parabéns pela iniciativa!

**Comment by gabrielhof** [comment]
Também estou com o mesmo problema.
Além disso, quando informe algum período diferente do mês atual não recebo movimentações de receitas.

Alguma possível solução pra esse problema?

**Comment by alexwbuschle** [comment]
Boa tarde @lfwroseiro e @gabrielhof

Acabou de ir para o ar uma alteração na api rest.

Nos testes aqui filtrou certinho. Só não consegui replicar seu problema @gabrielhof . Se ainda estiver acontecendo só dar um toque ;)

**Comment by gabrielhof** [comment]
@alexwbuschle ok, vou fazer um teste aqui e te comunico.

**Comment by gabrielhof** [comment]
Fiz um teste via postman. Não estou recebendo nenhum registro que tenha o campo `amount_cents` com números positivos quando filtro pelo mês de maio (`https://api.organizze.com.br/rest/v2/transactions?start_date=2019-05-01&end_date=2019-05-31`).
Existe alguma maneira em que eu possa isolar o problema? Talvez algum servidor de teste ou talvez criar uma conta nova só para isso?

**Comment by joaomedeiros95** [comment]
Estou tendo o mesmo problema do @gabrielhof, a alguns dias atrás estava tudo funcionando com o transactions mas hoje só está retornando transactions de débito as de receita não estão retornando. Não sei se foi alguma atualização na API de vocês mas a 1 ou 2 semanas atrás funcionava normal.

Alguma ideia @alexwbuschle?

**Comment by alexwbuschle** [comment]
@gabrielhof @joaomedeiros95 não consegui replicar aqui o problema.

O fix que subi esses dias era referente a filtragem por datas, que antes pegava o mês das datas passadas ao invés das datas exatas.

Uma coisa que percebi, é que não estava sendo ordenado os lançamentos pela data do mesmo, assim ficando pelo id, mas corrigi isso agora de manhã.

Já relacionado a filtragem de receita ou despesa, não consegui simular. A única filtragem que tem é pela data mesmo. Vocês conseguem criar uma conta nova e replicar esse problema?

**Comment by gabrielhof** [comment]
Claro. Vou tentar fazer isso esse fim de semana e te dou um retorno aqui.
Talvez o cenário do problema seja mais complexo do que eu estava imaginando.
