### ISSUE TITLE
Listar movimentações - Retorno limitado

### ISSUE THREAD

**Issue by diogo-cvs** [organizze/api-doc#27]
Verifiquei que o endpoint é limitado a 100 registros, é possível deixar isso aberto e retornar tudo?

**Comment by alexwbuschle** [comment]
@diogo-cvs deixar sem limit ficaria inviável por questões de performance, mas estamos alterando o limite de 100 para 300. 

Por enquanto a gente não tem paginação de registros, então a alternativa (por enquanto) seria filtrar pelas datas em um range menor.

**Comment by diogo-cvs** [comment]
Estou fazendo a busca day-by-day multi-thread, foi a melhor saída que
encontrei por conta da paginação.

Em qui, 1 de ago de 2019 às 11:05, Alex Buschle <notifications@github.com>
escreveu:

**Comment by alexwbuschle** [comment]
Vou fechar essa issue. Quando tiver disponível paginação dentro de um range de data, a gente da um toque ;)
