### ISSUE TITLE
como posso adicionar um centro de custo a uma transação?

### ISSUE THREAD

**Issue by thales91** [organizze/api-doc#3]
Ola
como posso adicionar dados de centro de custo a uma transação?
também estou tentando criar e recuperar centro de custo não estou conseguindo na API só via UI

**Comment by esdras** [comment]
Oi @thales91, obrigado por notificar a gente sobre este problema, como a API era usada primariamente na versão pessoal, esquecemos do atributo centro de custo. Agora basta passar o cost_center_id como atributo e o centro de custo será atribuído.

Eu também vou atualizar o README pra apontar a URL correta do centro de custo que é `https://api.organizze.com.br/rest/v2/cost_centers` e não `cost-centers` como aparece ali.

Desculpe o transtorno. Já enviei a correção, dentro de uns 10 minutos ela estará em produção.

[]s

**Comment by thales91** [comment]
@esdras  obrigado funcionou aqui
