### ISSUE TITLE
/balances retornando 404

### ISSUE THREAD

**Issue by aericson** [organizze/api-doc#30]
olá,

estive usando até hoje a api. Mas hoje um dos endpoint parou de funcionar.
`/balances?account_id={id}` está retornando 404 agora.

Esse endpoint não está documentado no README mas foi mencionado em:
https://github.com/organizze/api-doc/issues/11
e
https://github.com/organizze/api-doc/issues/21

é algum erro temporário ou tem algum outro endpoint que posso usar para obter o saldo de uma conta.

Obrigado!

**Comment by alexwbuschle** [comment]
e ae @aericson tudo tranquilo?
Cara, foi algo temporário mesmo. Já estamos com o endpoint de volta ;)

**Comment by aericson** [comment]
Funcionou \o/. Obrigado!
