### ISSUE TITLE
Lançamento parcelado

### ISSUE THREAD

**Issue by lbguilherme** [organizze/api-doc#37]
Estou integrando com vocês através da API documentada em https://github.com/organizze/api-doc. Em particular, estou tentando criar lançamentos parcelados. Pela documentação devo utilizar o endpoint `POST /transactions` passando `"installments_attributes": {"periodicity": "monthly", "total": 12}` para um lançamento de 12x. No entanto ao fazer isso o lançamento é criado sem parcelamento, como se esse atributo não estivesse lá.

É um erro da documentação?
Como devo proceder?

**Comment by rhuanbarreto** [comment]
@esdras confirmo que não está funcionando também. Poderia verificar?
