### ISSUE TITLE
Obter faturas antigas

### ISSUE THREAD

**Issue by dayanfcosta** [organizze/api-doc#38]
Eu percebi que só é possível obter faturas do ano corrente, não é possível obter faturas de anos passados?

**Comment by dayanfcosta** [comment]
É possível utilizando os filtros de `start_date` e `end_date`

**Comment by samuelrvg** [comment]
URL:
https://api.organizze.com.br/rest/v2/transactions&start_date=2018-09-01&end_date=2018-09-30

Esta retornando

{
    "error": "not found"
}

Estou conseguindo trazer somente do mês atual. 
Movimentações passadas com esse filtro não estão funcionando como deveria.
