### ISSUE TITLE
Id para integração 

### ISSUE THREAD

**Issue by thales91** [organizze/api-doc#4]
Olá estou integrando um sistema terceiro com o organizze e vamos criar muitas transações e vai ter casos de reembolço que vamos ter que deletar algumas transações se na api de vcs tivesse um idexterno em que eu pudesse deletar  ou somente fazer um filtro por esse idexterno seria uma ótima feature pra mim que evitaria que eu tivesse que ter um banco de integração só pra fazer um de para de de IDs o ideal que esse campo fosse um campo do tipo string

**Comment by esdras** [comment]
Eu não sei se entendi muito bem o teu problema, o id da transação que tem hoje não te ajuda? Podes explicar melhor, por gentileza? Você pode excluir movimentações através da API.

**Comment by thales91** [comment]
no caso eu queria uma forma de identificar uma transação que veio de uma integração pra que eu possa facilmente identificar

**Comment by esdras** [comment]
É difícil visualizar a tua necessidade com apenas essa descrição. Você quer saber se uma movimentação veio do Organizze ou não? O id da movimentação não é suficiente?

**Comment by thales91** [comment]
deixe me ver se consigo explicar melhor 
em um e-commerce é vendido um produto imediatamente crio uma transação no organizze 1 dia depois o cliente cancela a compra e eu tenho que deletar a transação no organizze pois a venda foi cancelada eu queria uma forma de encontrar essa venda no organize sem ter que criar um banco pra guardar que a venda X é a transação Y

**Comment by esdras** [comment]
Agora ficou claro o que está tentando fazer. Realmente você vai precisar de uma tabela associativa para associar o pedido com a movimentação. No momento não é possível trabalhar com outro identificador além do id da transaction. 😞

**Comment by thales91** [comment]
ok obrigado
