### ISSUE TITLE
IDs negativos para lançamentos da consulta /credit_cards/x/invoices/y

### ISSUE THREAD

**Issue by cirinor** [organizze/api-doc#41]
Prezados, boa tarde.

Primeiro gostaria mais uma vez parabenizá-los pela disponibilização da API a nós clientes do Organizze.

Então.. ao atualizar uma rotina pessoal que faz uso da API, percebi um comportamento diferente em relação à chave id disponibilizada através do endereço: GET /credit_cards/x/invoices/y. Ocorre que para 19 lançamentos o id veio negativo. Ao observar na consulta principal de lançamentos (GET/transactions), esses 19 negativos não possuem correspondentes.
Dessa forma, imagino que a API deva estar com alguma versão antiga para a consulta GET /credit_cards/x/invoices/y. Esse palpite é baseado nas verificações que fiz na minha conta pela versão web: os ids são outros e não são negativos, ou seja, nenhum problema para a aplicação web nem mobile.

Posso compartilhar mais informações com vocês caso seja necessário.

Sei que vcs devem ter inúmeras outras prioridades e um número reduzido de clientes utilizem a API, mas se for algo simples de resolver, ficarei grato.  : )

Abaixo seguem alguns dos ids:

![api_organizze_id_negativo](https://user-images.githubusercontent.com/588307/140934592-96ca0a97-d824-41dd-93bf-bea6328210ad.png)

**Comment by RenanGirard** [comment]
@cirinor você está conseguindo acessar a API? tentei no final de semana mas aparece como not found. :/

**Comment by esdras** [comment]
Oi Sr. Cirino, tudo bem?

Desculpe a demora.

Vou analisar esta questão e te retorno até segunda-feira.

Obrigado por reportar.

**Comment by esdras** [comment]
Oi Sr. Cirino.

Eu verifiquei aqui e não encontrei os registros com id negativo. Podes por gentileza fazer a mesma request pra API novamente, pra ver se eles ainda se encontram lá?

Muito obrigado.

**Comment by cirinor** [comment]
Bom dia, Esdras.

Enviei ontem a mesma request e ainda obtive valores negativos para ids da entidade credit_cards.

![image](https://user-images.githubusercontent.com/588307/144036627-870f8e2b-26bb-4a6f-ad45-0b865500083b.png)

**Comment by esdras** [comment]
Oi Cirino, bom dia.

To vendo que os valores negativos estão perto do valor máximo que o valor
máximo que um signed integer de 32 bit consegue
representar. (2.147.483.647).
Faz pouco tempo que a gente estourou a casa de 32bits para ids de
movimentações. Tivemos downtime pra mudar a coluna para 64bits.
Provavelmente o cliente que você está usando está se perdendo com os
valores > 32bits e convertendo representando eles como valores negativos.
Isso também faz sentido se você pensar que o bit mais significante é
usado para determinar o sinal.

Faz sentido? Tenta fazer a mesma requisição usando outro cliente (Postman,
por exemplo)

No banco de dados não há valores negativos, por isso suspeito que deve ser
o cliente da API que está se perdendo.

Estou à disposição para esclarecer melhor.

**Comment by cirinor** [comment]
Boa tarde, Esdras.

Faz sentido sim. Fiz a requisição com outro cliente e obtive os ids corretos. Problema do lado de cá mesmo. :)

Muito obrigado pela força!
