### ISSUE TITLE
Erro 500 ao criar categoria

### ISSUE THREAD

**Issue by rafaels-dev** [organizze/api-doc#42]
Olá!

Tentei criar uma categoria através de POST na URL https://api.organizze.com.br/rest/v2/categories com o seguinte corpo:
```json
{
  "name":"Investimentos / Carro Novo" 
}
```
Mas recebi erro 500 com mensagem genérica.

**Comment by rodrigoroldan** [comment]
@rafaels-dev conseguiu resolver?
Consigo criar subcategorias, mas categorias primárias não...
