### ISSUE TITLE
Erro 500 ao tentar gerar token

### ISSUE THREAD

**Issue by thiagob** [organizze/api-doc#43]
Ao tentar gerar meu token de acesso na url https://app.organizze.com.br/configuracoes/api-keys recebo HTTP 500.

**Comment by ribeiropaulor** [comment]
A URL correta tem que incluir o número da sua conta junto a Organizze.

https://app.organizze.com.br/<NÚMERO DA CONTA>/configuracoes/api-keys

Esse número está na URL que você acessa o app pelo navegador.

Exemplo:
https://app.organizze.com.br/1234/configuracoes/api-keys
