### ISSUE TITLE
Transações

### ISSUE THREAD

**Issue by ViniciosOliveira** [organizze/api-doc#44]
Existe alguma forma de puxar transações em um periodo de 1 ou 2 anos, ou algum serviço de webhook

**Comment by esdras** [comment]
Oi @ViniciosOliveira 

Consegues usar a paginação pra isso? 

Veja o exemplo abaixo usando curl e passando os parâmetros start_date, end_date pra listar transações.

`curl -H "Content-Type: application/json" -H "User-Agent: Meu App meuapp@example.com" -u "falecom@oesdras.com.br:a1926f988856bc9adfba16566962ae71e62588ce"  -v https://api.organizze.com.br/rest/v2/transactions?start_date=2021-01-01&end_date=2023-01-31
`

Qualquer dúvida estou à disposição.
