### ISSUE TITLE
Inclusão de tags

### ISSUE THREAD

**Issue by guilhermeapluz** [organizze/api-doc#49]
Olá, pessoal.
Tudo bem?

Estou trabalhando em uma integração do organizze com o meu banco, porém não estou conseguindo incluir as tags. Sempre retorna o erro 500. Alguém mais com este problema? Ou algo que eu esteja fazendo errado?

![image](https://github.com/organizze/api-doc/assets/4459299/9314adc6-c6b7-491b-a5ac-51514bf9f6ea)
![image](https://github.com/organizze/api-doc/assets/4459299/9d7e0ede-b9c0-4669-b30a-931bb385c321)

**Comment by GGontijo** [comment]
Testei aqui e deu certo.. Porém olhando sua request, ela está correta.

Existe alguma movimentação com essa tag no seu Organizze? 
- Confere se o identificador da TAG está correto e se estiver, crie uma movimentação manual inserindo a tag e tente novamente.
- Teste o consumo sem o envio da TAG para isolar o problema na TAG.
- Recrie a TAG e tente de novo 


![image](https://github.com/organizze/api-doc/assets/38219914/544e39d7-2b13-4acf-bd0e-3760a43cdf0a)
![image](https://github.com/organizze/api-doc/assets/38219914/339a25ec-5c5a-4ed5-aebf-6e58cbc1b882)

**Comment by guilhermeapluz** [comment]
Valeu pelo retorno.
Eu já tinha feito estes testes, tanto que to usando sem as tags até que eu consiga resolver isso.
Eu estava passando um dict na chamada do endpoint. Converti o dict pra json com json.dumps() e o erro 500 não aconteceu mais, porém as tags não foram criadas.

Mas como tu ta conseguindo fazer essa integração, certeza que é algum problema aqui que eu não consegui identificar ainda.

**Comment by GGontijo** [comment]
Entendi, espero que consiga resolver. Quando encontrar o problema compartilha aqui 😄

**Comment by esdras** [comment]
@GGontijo conseguiu resolver o problema?

**Comment by GGontijo** [comment]
opa, jóia? o usuário afetado é o @guilhermeapluz

**Comment by esdras** [comment]
Obrigado @GGontijo, aguardando o @guilhermeapluz

**Comment by guilhermeapluz** [comment]
Boa tarde, pessoal.
Não parei mais pra ver essa situação desde então, mas testando aqui ainda não estou conseguindo fazer o post com as tags.

**Comment by guilhermeapluz** [comment]
Gurizada.
Agradeço a ajuda, mas fui noob aqui. Eu estava esquecendo do json.dumps(), mas o engraçado é que sem as tags estava funcionando tudo perfeitamente.

Enfim.

**Comment by guilhermeapluz** [comment]
Gurizada.
Agradeço a ajuda, mas fui noob aqui. Eu estava esquecendo do json.dumps(), mas o engraçado é que sem as tags estava funcionando tudo perfeitamente.

Enfim.
