### ISSUE TITLE
parametro paid da transaction esta funcionando?

### ISSUE THREAD

**Issue by thales91** [organizze/api-doc#5]
ola estou tentando atualizar o paid para true mas o servidor esta me retornando erro 500

**Comment by esdras** [comment]
Oi @thales91, desculpe por isso. Já corrigi o problema, podes tentar novamente e confirmar se o problema foi corrigido, por gentileza?

**Comment by thales91** [comment]
testei aqui e consegui atualizar 
obrigado

**Comment by esdras** [comment]
\o/
