### ISSUE TITLE
não consigo mais autenticar minha aplicação

### ISSUE THREAD

**Issue by buruno** [organizze/api-doc#50]
olá, por acaso houve alguma mudança no backend? de um mês para outro passei a não conseguir mais me autenticar na API, e quando abri um ticket no suporte eles sugeriram tentar uma outra API key, o que também não funcionou.

**Comment by GGontijo** [comment]
poderia encaminhar print da request e response?

**Comment by GGontijo** [comment]
Olá, acabei de testar aqui e parece que não houve alteração. Você tentou outros endpoints ou com outros filtros? 

Há alguns meses teve uma transação que criei pela plataforma que subiu bugada então sempre que essa transação entrava no response de "/transactions" a API retornava erro. A requisição só funcionava se eu filtrasse fora do período dela.

Precisei encontrar essa transação deduzindo pelos filtros e deletar ela, daí normalizou.

**Comment by buruno** [comment]
hm, boa sugestão, mais tarde vou fazer esses testes. hoje minha esposa também percebeu que há algumas incongruências dentro do próprio painel do Organizze, pode ter algo a ver também

**Comment by GGontijo** [comment]
Avisa aqui quando encontrar o problema 😄

**Comment by esdras** [comment]
@buruno Estou resolvendo problemas da API hoje. Eu fiz testes de autenticação aqui e aparentemente está tudo ok. Podes me informar melhor sobre o teu problema?
Perdoem a demora pra responder as issues, a gente fez uma migração de banco de dados e isso acabou ocupando todo o time. Estou à disposição.

**Comment by buruno** [comment]
olá @esdras, recebi uma resposta do suporte e consegui me autenticar hoje com CURLOPT_USERPWD, o que é estranho porque até então (desde 2019?) estava usando basic auth (não lembro como gerei o token). 

mas enfim, resolvido!
