### ISSUE TITLE
quando atualizo o paid de uma transaction a despesa se transforma em renda

### ISSUE THREAD

**Issue by thalessfmg** [organizze/api-doc#6]
quando atualizo o paid de uma transaction a despesa se transforma em renda

**Comment by esdras** [comment]
Oi @thalessfmg 
Muito obrigado por reportar, já enviei a correção. Podes confirmar se está tudo bem agora, por gentileza?

Grato.

**Comment by thalessfmg** [comment]
show vou ver aqui
obrigado

**Comment by thalessfmg** [comment]
funcionou perfeito obrigado

**Comment by esdras** [comment]
Show!
