### ISSUE TITLE
Não consigo me autenticar

### ISSUE THREAD

**Issue by HerrTuring** [organizze/api-doc#60]
Admito que é a primeira vez que eu uso Basic Http Auth. Mas o conceito não podia ser mais simples. Uma rápida pesquisa e na teoria esse código deveria funcionar:

![Screenshot 2024-11-17 172334](https://github.com/user-attachments/assets/3cb5a00d-3a9a-40a9-b7c1-460349c1965d)

O e-mail censurado é o e-mail da minha conta, e o código após o ":" é o api key que consegui no caminho: https://app.organizze.com.br/configuracoes/api-keys

Qualquer caminho que eu uso resulta sempre em erro 401 com o corpo da resposta: 
```{"error":"Não autorizado"}```

Tentei outras abordagens como usar:
```Buffer.from("").toString("base64")``` 

Ou montar o headers com 
```new Header()```

Porém tudo da no mesmo resultado.

**Comment by luishgp** [comment]
Mesmo problema aqui. 

Faz alguns meses que não faço nada pela API, hoje quando fui rodar um script que faz de/para de lançamentos, vi que não está autenticando... 

```
> GET /rest/v2/transactions?start_date=2024-11-01&end_date=2024-11-31&credit_card_id=XXX HTTP/2
> Host: api.organizze.com.br
> user-agent: Lus Henrique (EMAIL)
> content-type: application/json; charset=utf-8
> authorization: Basic (base64 geardo pelo insomnia contendo EMAIL:TOKEN_ACESSO)
> accept: */*
```

**Comment by HerrTuring** [comment]
> Mesmo problema aqui.
> 
> Faz alguns meses que não faço nada pela API, hoje quando fui rodar um script que faz de/para de lançamentos, vi que não está autenticando...
> 
> ```
> > GET /rest/v2/transactions?start_date=2024-11-01&end_date=2024-11-30 HTTP/2
> > Host: api.organizze.com.br
> > user-agent: Lus Henrique (EMAIL)
> > content-type: application/json; charset=utf-8
> > authorization: Basic (base64 gerado pelo Insomnia contendo EMAIL:TOKEN_ACESSO)
> > accept: */*
> ```
> 
> Status de resposta 401:
> 
> ```json
> {"error":"Não autorizado"}
> ```

No seu caso o seu acesso de api funcionava e só parou de funcionar do nada? Eu me cadastrei a pouco tempo então tava assumindo que o problema era com a minha conta, já que não tem mais ninguém reclamando aqui no github.

**Comment by luishgp** [comment]
O meu do jeito que estava aqui funcionava, mas agora não mais, mesmo recriando o token.

**Comment by HerrTuring** [comment]
> Entrei em contato com o suporte e consegui conectar novamente @HerrTuring.
> 
> Verifica aí se deu certo, qualquer coisa tento lhe ajudar!

Eu também já tava em contato com suporte esse tempo, mas não me responderam ainda ao último questionamento que fiz. De qualquer jeito, testei aqui o meu código acima e dessa vez rodou. Devia ser um problema geral. Valeu.
