### ISSUE TITLE
nao estou conseguindo mais usar a api

### ISSUE THREAD

**Issue by thalessfmg** [organizze/api-doc#7]
esta dando erro 401 mesmo passando o authorization correto

**Comment by esdras** [comment]
Oi @thalessfmg, já estamos verificando.

**Comment by esdras** [comment]
Oi @thalessfmg, podes tentar novamente? Aparentemente você estava tentando acessar uma rota inexistente e isso estava causando um erro. Agora estamos tratando esse caso e retornando 404.
Estou à disposição.

**Comment by esdras** [comment]
Confirmei aqui, além do erro da rota inexistente, realmente havia um problema na autenticação. Corrigido. Muito obrigado por reportar o Problema @thalessfmg

**Comment by thalessfmg** [comment]
@esdras voltou ao normal muito obrigado
