### ISSUE TITLE
start_date / end_date não funciona

### ISSUE THREAD

**Issue by Jonatasmz** [organizze/api-doc#9]
Não consegui fazer o start_date funcionar corretamente, estou recebendo sempre as transações do mês atual.

EX:
https://api.organizze.com.br/rest/v2/transactions.json?start-date=2017-06-01&end-date=2017-06-30

**Comment by Jonatasmz** [comment]
Entendi o problema. É start_date não start-date.
Por favor alterar a documentação em Paginação.

**Comment by esdras** [comment]
Corrigido, obrigado por reportar.
